-- Holiday Concierge data model
-- Run in Supabase SQL editor before using concierge account features.

create extension if not exists pgcrypto;

create table if not exists holiday_agent_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique,
  household jsonb not null default '{}'::jsonb,
  preferences jsonb not null default '{}'::jsonb,
  visited_destinations text[] not null default '{}',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists holiday_agent_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  status text not null default 'collecting',
  draft jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists holiday_agent_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references holiday_agent_sessions(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists holiday_agent_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  session_id uuid references holiday_agent_sessions(id) on delete set null,
  search_payload jsonb not null,
  recommendations jsonb not null,
  agent_brief jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists holiday_agent_jobs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  session_id uuid references holiday_agent_sessions(id) on delete set null,
  status text not null default 'queued',
  search_payload jsonb not null,
  result_plan_id uuid references holiday_agent_plans(id) on delete set null,
  error text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create table if not exists holiday_agent_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  kind text not null default 'consultation_ready',
  title text not null,
  body text not null,
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists holiday_agent_admins (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique,
  email text,
  notes text,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table if not exists holiday_agent_system_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  scope text not null,
  event text not null,
  level text not null default 'info',
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_holiday_agent_sessions_user_id on holiday_agent_sessions(user_id, updated_at desc);
create index if not exists idx_holiday_agent_messages_session_id on holiday_agent_messages(session_id, created_at asc);
create index if not exists idx_holiday_agent_plans_user_id on holiday_agent_plans(user_id, created_at desc);
create index if not exists idx_holiday_agent_jobs_user_id on holiday_agent_jobs(user_id, created_at desc);
create index if not exists idx_holiday_agent_jobs_status on holiday_agent_jobs(status, created_at asc);
create index if not exists idx_holiday_agent_notifications_user_id on holiday_agent_notifications(user_id, created_at desc);
create index if not exists idx_holiday_agent_admins_user_id on holiday_agent_admins(user_id);
create index if not exists idx_holiday_agent_system_logs_created_at on holiday_agent_system_logs(created_at desc);
create index if not exists idx_holiday_agent_system_logs_scope on holiday_agent_system_logs(scope, created_at desc);

alter table holiday_agent_profiles enable row level security;
alter table holiday_agent_sessions enable row level security;
alter table holiday_agent_messages enable row level security;
alter table holiday_agent_plans enable row level security;
alter table holiday_agent_jobs enable row level security;
alter table holiday_agent_notifications enable row level security;
alter table holiday_agent_admins enable row level security;
alter table holiday_agent_system_logs enable row level security;

-- Profile policies
drop policy if exists "profiles_select_own" on holiday_agent_profiles;
create policy "profiles_select_own" on holiday_agent_profiles
for select using (auth.uid() = user_id);

drop policy if exists "profiles_insert_own" on holiday_agent_profiles;
create policy "profiles_insert_own" on holiday_agent_profiles
for insert with check (auth.uid() = user_id);

drop policy if exists "profiles_update_own" on holiday_agent_profiles;
create policy "profiles_update_own" on holiday_agent_profiles
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Session policies
drop policy if exists "sessions_select_own" on holiday_agent_sessions;
create policy "sessions_select_own" on holiday_agent_sessions
for select using (auth.uid() = user_id);

drop policy if exists "sessions_insert_own" on holiday_agent_sessions;
create policy "sessions_insert_own" on holiday_agent_sessions
for insert with check (auth.uid() = user_id);

drop policy if exists "sessions_update_own" on holiday_agent_sessions;
create policy "sessions_update_own" on holiday_agent_sessions
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Message policies (via session ownership)
drop policy if exists "messages_select_own" on holiday_agent_messages;
create policy "messages_select_own" on holiday_agent_messages
for select using (
  exists (
    select 1 from holiday_agent_sessions s
    where s.id = holiday_agent_messages.session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists "messages_insert_own" on holiday_agent_messages;
create policy "messages_insert_own" on holiday_agent_messages
for insert with check (
  exists (
    select 1 from holiday_agent_sessions s
    where s.id = holiday_agent_messages.session_id
      and s.user_id = auth.uid()
  )
);

-- Plan policies
drop policy if exists "plans_select_own" on holiday_agent_plans;
create policy "plans_select_own" on holiday_agent_plans
for select using (auth.uid() = user_id);

drop policy if exists "plans_insert_own" on holiday_agent_plans;
create policy "plans_insert_own" on holiday_agent_plans
for insert with check (auth.uid() = user_id);

-- Job policies
drop policy if exists "jobs_select_own" on holiday_agent_jobs;
create policy "jobs_select_own" on holiday_agent_jobs
for select using (auth.uid() = user_id);

drop policy if exists "jobs_insert_own" on holiday_agent_jobs;
create policy "jobs_insert_own" on holiday_agent_jobs
for insert with check (auth.uid() = user_id);

drop policy if exists "jobs_update_own" on holiday_agent_jobs;
create policy "jobs_update_own" on holiday_agent_jobs
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Notification policies
drop policy if exists "notifications_select_own" on holiday_agent_notifications;
create policy "notifications_select_own" on holiday_agent_notifications
for select using (auth.uid() = user_id);

drop policy if exists "notifications_insert_own" on holiday_agent_notifications;
create policy "notifications_insert_own" on holiday_agent_notifications
for insert with check (auth.uid() = user_id);

drop policy if exists "notifications_update_own" on holiday_agent_notifications;
create policy "notifications_update_own" on holiday_agent_notifications
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Admin policies
drop policy if exists "admins_select_own" on holiday_agent_admins;
create policy "admins_select_own" on holiday_agent_admins
for select using (auth.uid() = user_id);

drop policy if exists "admins_update_own" on holiday_agent_admins;
create policy "admins_update_own" on holiday_agent_admins
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- System logs are admin-only through backend service role APIs.
drop policy if exists "system_logs_no_client_read" on holiday_agent_system_logs;
create policy "system_logs_no_client_read" on holiday_agent_system_logs
for select using (false);
